create table
  public.potions_catalog (
    sku text not null,
    created_at timestamp with time zone not null default now(),
    quantity integer not null default 0,
    price integer not null default 0,
    constraint potions_catalog_pkey primary key (sku),
    constraint potions_catalog_sku_key unique (sku)
  ) tablespace pg_default;

-- Insert the initial rows
INSERT INTO public.potions_catalog (sku, quantity, price)
VALUES ('[50,50,0,0]', 0, 1),
       ('[0,50,50,0]', 0, 1),
       ('[50,0,50,0]', 0, 1);

create table
  public.global_inventory (
    id integer generated by default as identity,
    gold integer null default 100,
    num_red_ml integer not null default 0,
    num_green_ml integer not null default 0,
    num_blue_ml integer not null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_items (
    cart_item_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    quantity integer not null default 0,
    cart_id bigint not null,
    sku text not null,
    constraint cart_items_pkey1 primary key (cart_item_id),
    constraint cart_items_cart_item_id_key unique (cart_item_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references cart (cart_id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.cart (
    cart_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    customer_name text not null,
    constraint cart_items_pkey primary key (cart_id)
  ) tablespace pg_default;